import { useRef, useState } from 'react'
import { AlertCircle, ArrowRight, Check, CheckCircle2, Clock3, FileSearch, FileText, Gauge, LockKeyhole, ScanText, ShieldCheck, Sparkles, TriangleAlert, UploadCloud } from 'lucide-react'
import { PageHeader } from '../components/AppShell'

const risks = [
  { level: 'high', title: 'Unlimited indemnity', clause: 'Clause 11.2', copy: 'The supplier indemnifies all losses without a financial cap or exclusion for indirect loss.', fix: 'Cap aggregate liability at fees paid in the prior 12 months.' },
  { level: 'medium', title: 'One-sided termination', clause: 'Clause 14.1', copy: 'The customer may terminate on 7 days’ notice, while the supplier has no equivalent right.', fix: 'Add a mutual termination right and a reasonable cure period.' },
  { level: 'medium', title: 'Data-processing gap', clause: 'Clause 8', copy: 'Personal data is referenced without defining controller/processor roles or breach notice timing.', fix: 'Add a Kenya DPA schedule with roles, purpose, safeguards, and incident notification.' },
]

export function ContractPage() {
  const [stage, setStage] = useState<'empty' | 'scanning' | 'result'>('empty')
  const clauseRefs = useRef<Record<string, HTMLDetailsElement | null>>({})
  function scan() { setStage('scanning'); setTimeout(() => setStage('result'), 1700) }
  function openClause(title: string) {
    const details = clauseRefs.current[title]
    if (!details) return
    details.open = true
    details.scrollIntoView({ behavior: 'smooth', block: 'center' })
  }
  return <div className="page contract-page"><PageHeader eyebrow="Katiba OS · Contract Engine" title="Turn legal text into an obligation map." copy="Upload, extract, compare, and review—without losing the clause-level source." action={stage === 'result' ? <button className="button button-light" onClick={() => setStage('empty')}>Analyze another</button> : undefined} />
    {stage === 'empty' && <section className="contract-start"><article className="card contract-drop"><span className="contract-upload-icon"><UploadCloud /></span><h2>Drop a contract here</h2><p>PDF or DOCX · up to 25 MB · originals remain unchanged</p><button className="button button-primary" onClick={scan}><FileSearch /> Load sample supplier agreement</button><small><LockKeyhole /> Private processing workspace</small></article><aside className="contract-how"><span className="section-label">What happens next</span><div><span>1</span><p><strong>Structure</strong><small>Extract parties, clauses, dates, money, and obligations.</small></p></div><div><span>2</span><p><strong>Compare</strong><small>Check deviations against a Kenyan SME playbook.</small></p></div><div><span>3</span><p><strong>Explain</strong><small>Show risk, why it matters, and a review-ready alternative.</small></p></div></aside></section>}
    {stage === 'scanning' && <section className="card contract-scanning" role="status"><div className="scan-animation"><span><ScanText /></span><i /><i /><i /></div><h2>Reading the agreement structure…</h2><p>Extracting 28 clauses, 9 obligations, dates, and liability language.</p><div className="scan-steps"><span className="done"><Check />Text extracted</span><span className="active"><Sparkles />Comparing playbook</span><span><Clock3 />Building obligation map</span></div></section>}
    {stage === 'result' && <div className="contract-results"><header className="card contract-result-head"><div className="contract-file"><span><FileText /></span><p><strong>MetroBuild_Supplier_Agreement.pdf</strong><small>18 pages · analyzed just now</small></p></div><div className="contract-health"><span>Contract health</span><strong>64<small>/100</small></strong><i><b style={{ width: '64%' }} /></i></div><div className="contract-head-stats"><span><strong>28</strong><small>clauses</small></span><span><strong>9</strong><small>obligations</small></span><span className="risk-number"><strong>3</strong><small>risks</small></span></div></header>
      <div className="contract-result-grid"><section><article className="card contract-summary"><div className="card-title"><div><span className="section-label">Executive review</span><h2>Commercially usable, but liability and data terms need revision.</h2></div><span className="ai-badge"><Sparkles /> AI structured</span></div><p>The agreement clearly defines the services and payment schedule. Three clauses depart materially from the SME playbook; none should be accepted without a named reviewer.</p><div><span><CheckCircle2 />Clear scope</span><span><CheckCircle2 />Defined fees</span><span className="attention"><TriangleAlert />Liability imbalance</span><span className="attention"><AlertCircle />DPA gap</span></div></article>
        <div className="contract-risk-list">{risks.map((risk) => <article className={`card contract-risk risk-${risk.level}`} key={risk.title}><span className="risk-icon">{risk.level === 'high' ? <AlertCircle /> : <TriangleAlert />}</span><div><span className="risk-label">{risk.level} risk · {risk.clause}</span><h3>{risk.title}</h3><p>{risk.copy}</p><details ref={(element) => { clauseRefs.current[risk.title] = element }}><summary>Suggested review position <ArrowRight /></summary><p>{risk.fix}</p></details></div><button className="button button-light" onClick={() => openClause(risk.title)}>Open clause</button></article>)}</div></section>
        <aside className="contract-side"><article className="card obligation-card"><div className="card-title"><div><span className="section-label">Upcoming obligations</span><h2>First 30 days</h2></div><Gauge /></div><div><span><i>01</i><p><strong>Provide implementation plan</strong><small>Supplier · within 5 days</small></p></span><span><i>02</i><p><strong>Pay onboarding fee</strong><small>Customer · KES 120,000</small></p></span><span><i>03</i><p><strong>Appoint data contacts</strong><small>Both parties · before processing</small></p></span></div></article><article className="card contract-guardrail"><ShieldCheck /><h2>Explainable by design</h2><p>Every risk opens the original clause and named playbook rule. No clause is changed automatically.</p></article></aside></div>
    </div>}
  </div>
}
