import { Check, Database, EyeOff, Fingerprint, KeyRound, LockKeyhole, RotateCcw, ServerCog, ShieldCheck, UserCheck } from 'lucide-react'
import { PageHeader } from '../components/AppShell'

const controls = [
  { icon: LockKeyhole, title: 'Encryption everywhere', copy: 'TLS in transit, field-level encryption for sensitive records, and managed keys in production.' },
  { icon: UserCheck, title: 'Role-based access', copy: 'Claimants see their own matters; reviewers see only assigned cases; admin access is auditable.' },
  { icon: EyeOff, title: 'Purpose limitation', copy: 'Evidence is processed only for the claim the person explicitly consented to.' },
  { icon: Fingerprint, title: 'Evidence integrity', copy: 'Originals remain immutable, with content hashes and a separate working copy for annotations.' },
  { icon: RotateCcw, title: 'Retention controls', copy: 'Case owners can export or request deletion; retention schedules are visible and enforceable.' },
  { icon: ShieldCheck, title: 'Human decision point', copy: 'No legal-effect decision or court submission is made solely by automated processing.' },
]

export function SecurityPage() {
  return <div className="page security-page"><PageHeader eyebrow="Trust center" title="Privacy is part of the product—not a footnote." copy="Designed around the Kenya Data Protection Act, legal confidentiality, and explainable automation." />
    <section className="security-hero card"><div><span className="trust-seal"><ShieldCheck /></span><span className="section-label">Current protection posture</span><h2>All demo controls healthy</h2><p>The prototype demonstrates the security model without claiming production certification.</p></div><div className="security-score"><strong>8/8</strong><span>core controls demonstrated</span></div><div className="security-checks"><span><Check />Consent record</span><span><Check />Access control</span><span><Check />Audit log</span><span><Check />Human review</span></div></section>
    <section className="control-grid">{controls.map(({ icon: Icon, title, copy }) => <article className="card" key={title}><span><Icon /></span><h3>{title}</h3><p>{copy}</p><small><Check /> Demonstrated in prototype</small></article>)}</section>
    <section className="architecture-section"><div className="architecture-copy"><span className="section-label">Security architecture</span><h2>Sensitive data has a short, visible path.</h2><p>Production deployment separates identity, case records, evidence objects, AI processing, and audit events. The AI receives the minimum necessary context and cannot query unrelated cases.</p><ul><li><Check />Kenya-region storage option</li><li><Check />Provider zero-retention mode where available</li><li><Check />Secrets held outside application code</li><li><Check />DPIA before real-world pilot</li></ul></div><div className="architecture-diagram" aria-label="Security architecture diagram"><div><span><UserCheck /></span><strong>Citizen or reviewer</strong><small>Passkey / OTP</small></div><i /><div><span><KeyRound /></span><strong>API gateway</strong><small>RBAC + rate limits</small></div><i /><div className="architecture-split"><span><span><Database /></span><strong>Case data</strong><small>Encrypted</small></span><span><span><ServerCog /></span><strong>AI enclave</strong><small>Minimum context</small></span></div></div></section>
    <section className="card legal-alignment"><div><span className="section-label">Kenya Data Protection Act alignment</span><h2>From principle to product control</h2></div><div className="alignment-table"><div><strong>Lawful, fair, transparent processing</strong><span>Plain-language consent and processing notice before analysis</span><b>Implemented</b></div><div><strong>Purpose and data minimization</strong><span>Per-case evidence scope; no unrelated case access</span><b>Implemented</b></div><div><strong>Data subject rights</strong><span>Export, correction, restriction, and deletion workflow</span><b>Prototype</b></div><div><strong>Automated decision safeguards</strong><span>Human reviewer required before legal action</span><b>Implemented</b></div><div><strong>Data protection impact assessment</strong><span>Required before any live sensitive-data pilot</span><b className="planned">Planned</b></div></div></section>
  </div>
}
